name: Run SQL test
on: [push]
jobs:
  run-stuff:
    runs-on: ubuntu-latest
    services:
      image: gvenzl/oracle-xe:11-slim
      ports:
        - 1521:1521
      env:
        ORACLE_RANDOM_PASSWORD=true
    steps:
      - uses: actions/checkout@v2
      - run: docker ps -a
